secret_env_variables:
    TELEGRAM_TOKEN: ENC[AES256_GCM,data:Lu67EyaDpXODoGNcMPL4w0quEGUJMfoVOBLDRJL1wA7jMw1C97hROb5jkZhSRg==,iv:hbY/8ylYaAAQ1kkzH03eew7ZQAt/wWXPtQ3diDMkjrE=,tag:ORpLCiulsaI96X6IYjuIHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-28T10:48:00Z"
    mac: ENC[AES256_GCM,data:5FmVGVQm+L1C/QMGxKhHI0Gmxb14Wey1F/V2s1hvn0aWolKyAzWXAiRqrnbGwbAGNnNWSKO5vYG4AwoNaQd0bIXqidd/1AvsfwEKpUhOTDcxjXMGuId8IrhN0Jn+DDzO4WuklsBxUDs/PoJiakwxBlbv8CzGr8u/8aBKqiWHMUE=,iv:dwZxG9Rdv79n0WuBh0bz/4SZrNKhHc77MgcqpcdvNPw=,tag:yQCA3w4CmH7gTb+DNrn4vw==,type:str]
    pgp:
        - created_at: "2024-12-21T15:18:44Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA+7ekPbCuJHsAQwAkIUv7ockd+ICw3Xei1yFIIJTwpCvn7Ra39DQd4X6mGMz
            xWj1e1Wca9XxQf6hgUDDPwwY7fGLWd6KTHQyxAR2fFqVyj/BRUmVubaYpP2rjhlx
            wlvWwkfr6NMmNctJ0MMFdsgl/hbwxtH8VccOyTBz7nObkW9KCnnw7CXUD/E8WGhb
            2oYKBegHc4z9VXiOqIXXhiP9EqlCkn5i9oJIyaeJxVq3ELibPmmBeQFqjIHg1bN2
            AcVURyc5+g9a/FkMJnncwD+Z9UwLIkeePYl1/YaUhs/IoIfWfL2ccgZBMQjzkOfK
            ekqvqoyH7Mgqx30AunGTS5RKjljn6rj1E5CD6sPvB9boUCHLcrxh4BzUIUDURbN3
            jL1VCZUWx40rLNRE7R6mcUe3D8IKhl1nVuHC7O/EzaoNqZT3HzDcSah6uy//Kf0+
            L1ZY+VQxxJNgKACLb1mUp82x9lKl8O/WZbswA8Nofj3/I06fz36CbcZf8Sk3zBNt
            m5/mz1skXi/dqwIXHfWR0l4Bn7RXDCwDM5qg14cc8MX4+7viU/EoMaFramFGwnur
            frvfmIjUAxZPGTROWp3qPoah/gB7hGKmVhY05SdI25b315vxfbmQoABShQwaABlK
            Vm+0dhYg3Vk17yD+lOmi
            =3ZiQ
            -----END PGP MESSAGE-----
          fp: D85C59ACB904856AF3D108A20DDE1A9CC421A97C
    unencrypted_suffix: _unencrypted
    version: 3.7.1
